<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>128x128-PNG-Trans.ico</ApplicationIcon>
    <UserSecretsId>8f04637e-ccb2-442b-8019-4f6b83c5cfa5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="128x128-PNG-Trans.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.7.1" />
    <PackageReference Include="Google.Apis.Auth" Version="1.77.0" />
    <PackageReference Include="Google.Apis.YouTube.v3" Version="1.77.0.4284" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
